### PR TITLE
Correct Problem with \iunit

### PR DESCRIPTION
**Pull request by svellala2001**

### CODE REVIEW

**Comment by physikerwelt** [comment]
... any updates here ?

**Comment by physikerwelt** [comment]
@svellala2001 can you review the style suggestions by
https://www.quantifiedcode.com/app/project/gh:DRMF:DRMF-Seeding-Project/diff/c0e8560d96aea68af598200f246906fe73c58e6e/7df591704465ac08512423659cdf1cdd820b795e/issues

Since they are generated by a computer, not all of them must make sense, but maybe some do.
So please check that and report the result here.

**Comment by physikerwelt** [comment]
With regard to the fixing of the tests in d41608a8678bd3f6d48237ea93750015128662fd:
I think that is a very nice solution to the problem we discussed.

**Comment by physikerwelt** [comment]
Have a look at https://landscape.io/diff/332575
Are these warnings relevant?

**Comment by physikerwelt** [comment]
:+1:
Nice work. This is really a significant improvement.
cc @HowardCohl

**Comment by HowardCohl** [comment]
I agree. This is great.

**Pull request merged**
