### PR TITLE
Change folder structure, add credits, (eventually) fix style issues

### PR DESCRIPTION
**Pull request by plato2000**
It makes more sense to have the folders named for what the code inside does rather than by who wrote it. To do this, credits were added to the beginning of every file. Along with this, folder structures were changed to have a src folder in each subproject. READMEs still need to be changed, and @physikerwelt needs to be added to the credits where he modified the files. Also, almost none of the files follow PEP-8 convention.

### CODE REVIEW

**Comment by physikerwelt** [comment]
@plato2000 please keep in mind that the PEP-8 standards are a nice goal, but might cause serious merge conflicts for all open changes.

**Comment by plato2000** [comment]
@physikerwelt I am aware of this possibility, so I have tried to not modify files that are under active development.

**Comment by plato2000** [comment]
@physikerwelt QuantifiedCode reports a failed check but when I click details, I don't get any high-severity issues. There are a few "potential bugs", but even those existed before I tried messing with the code.

**Comment by physikerwelt** [comment]
I really don't like the use of "file" as a variable name and also the *
import.
The other warning seem to be less severe.

**Comment by plato2000** [comment]
@physikerwelt I fixed the issues you mentioned. It seems that all of the issues though are in projects which are being replaced (@KChen1250 and @notjagan are doing a lot of it).

**Pull request merged**
