### PR TITLE
Upload project to GitHub

### PR DESCRIPTION
**Pull request by joonbang**

### CODE REVIEW

**Comment by physikerwelt** [comment]
@joonbang please review the suggestions at https://landscape.io/diff/341753

**Comment by physikerwelt** [comment]
what is the significance of the zip files?

**Comment by joonbang** [comment]
The zip files are just old backups of the program that I made before any major revision to the code.

**Comment by physikerwelt** [comment]
Maybe you can remove them from the repo?

**Comment by HowardCohl** [comment]
@physikerwelt @joonbang Were the zip files removed?

**Comment by physikerwelt** [comment]
@HowardCohl yes in 1dc0878 as you should be able to see above

**Comment by HowardCohl** [comment]
@physikerwelt Great! Thank you!

**Pull request merged**
