### PR TITLE
Create dlmf.py

### PR DESCRIPTION
**Pull request by pwang00**
Create a standalone DLMF TeX parser to be used with tex2Wiki.py, as to allow for use on both KLS and DLMF data sets.

### CODE REVIEW

**Comment by HowardCohl** [comment]
dlmf.py is a terrible name. (depending on what you think it is supposed to do.) If it's what I think it's for, it should be DLMFtex2Wiki.py.  However, I am really confused. What is dlmf.py supposed to do?

**Comment by physikerwelt** [comment]
@pwang00 well done now the next step is to fix the warnings https://landscape.io/diff/342785 in the same way as this was done at the other file.

**Comment by physikerwelt** [comment]
@pwang00 please focus on the DLMFtex2Wiki.py file and do not change other files.

**Comment by physikerwelt** [comment]
@pwang00 please focus on the DLMFtex2Wiki.py file and do not change other files.

**Comment by physikerwelt** [comment]
@pwang00 please remove the yellow needs improvement label once you are done

**Comment by physikerwelt** [comment]
@pwang00 please focus on the DLMFtex2Wiki.py file and do not change other files.

on https://github.com/DRMF/DRMF-Seeding-Project/pull/35/files I still see two files changed

**Comment by pwang00** [comment]
Wait I'm confused, I specifically made sure only to change and commit DLMFtex2Wiki.py.  I don't understand why tex2Wiki is showing up.

**Comment by pwang00** [comment]
Actually, I think the tex2Wiki was changed a while ago to fix the runtime errors.  How do I remove it from the files changed?

**Comment by physikerwelt** [comment]
@pwang00 sorry I'm in a hurry. Let me fix it for you really quick. However, I think we should work on a strategy together with @HowardCohl so that you learn how to use git.

**Comment by HowardCohl** [comment]
@pwang00 Philip, what you need to do is copy and replace with an old unchanged version of tex2Wiki.py, then it will no longer show up as an changed file.  BTW, Moritz already did this for you.

**Pull request merged**
