### PR TITLE
Added my eCF Mathematica to Latex files

### PR DESCRIPTION
**Pull request by KChen1250**

### CODE REVIEW

**Comment by KChen1250** [comment]
@physikerwelt is there a way to make exceptions to some files? Most of the apparent errors are being caused by Divya's old code, like "Omit `len()` for indexing/slicing"

**Comment by physikerwelt** [comment]
can you adjust the directory structure and create the following sub directories:

src --> the source code

test -> unit tests for the source

doc (or tex)--> the latex documents also create a .gitignore file https://gist.github.com/kogakure/149016

@HowardCohl can you help verifying that no data is uploaded that should not be on github

**Comment by HowardCohl** [comment]
@physikerwelt Can you show me where to look?

**Comment by physikerwelt** [comment]
@HowardCohl I'm not sure if I understand the question.
Please look at this pull request

**Comment by HowardCohl** [comment]
@KChen1250 @physikerwelt Holy cow! No! All those .sty files should not be there! Please remove them!

**Comment by HowardCohl** [comment]
@KChen1250 @physikerwelt Has Kevin's question about Divya's code been addressed?

**Comment by HowardCohl** [comment]
@KChen1250 @physikerwelt Please update the pull request removing the .sty files, (putting them in .gitignore).  After, I will check again, to make sure all files are kosher. Thanks for letting me know Moritz. Can you ask me again when the time is right?

@KChen1250 the style files are proprietary and should not appear publicly. This is a big issue. Come to talk to me about it when you come in again.

**Comment by HowardCohl** [comment]
@KChen1250 @physikerwelt  Also, 

```
Glossary.csv 
ZE.*.*
ak 
ak.*
macros.txt
newIdentities.*
newIdentitiesTest.*
test.*
x.log
```

should *all* be put in .gitignore.  I'd like to see this again, when everything is removed to do another check.

**Comment by physikerwelt** [comment]
@KChen1250 please remove the yellow 'needs improvement' flag after having fixed the issues

**Pull request closed without merging**
