### PR TITLE
Compare repository tex2Wiki and local tex2Wiki

### PR DESCRIPTION
**Pull request by physikerwelt**
Add new code into tex2Wiki (local version)
Fix unnecessary parentheses
Get rid of unnecessary comments

### CODE REVIEW

**Comment by physikerwelt** [comment]
@pwang00 Can you review the changes and merge after you checked them.

**Comment by physikerwelt** [comment]
@pwang00 Why don't you start with this task? It's really simple just push the "merge pull request button" or describe what needs to be changed.

**Comment by pwang00** [comment]
I don't think I can merge the pull request, since it says "Only those with write access to this repository can merge pull requests."

**Comment by physikerwelt** [comment]
@pwang00 yes. It's blocked by #34 ;-) So fix #34 first.

**Comment by pwang00** [comment]
Successfully merged.

**Comment by physikerwelt** [comment]
:+1:

**Pull request merged**
